[package]
name = "bustub"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "bustub-shell"
path = "src/shell.rs"

[dependencies]
comfy-table = "7.2.2"
rand = "0.8"
rustyline = "18.0.0"
sqlparser = {version = "0.62.0", features = ["serde"]}

[dev-dependencies]
rand = "0.8"
